In [2]:
import numpy as np

# Create a 2D NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Basic operations
sum_all = np.sum(array)
mean_all = np.mean(array)
transposed = array.T

print("Original array:\n", array)
print("Sum of all elements:", sum_all)
print("Mean of all elements:", mean_all)
print("Transposed array:\n", transposed)

Original array:
 [[1 2 3]
 [4 5 6]]
Sum of all elements: 21
Mean of all elements: 3.5
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
import seaborn as sns
import pandas as pd

import matplotlib.pyplot as plt

# Convert the NumPy array to a DataFrame for easier plotting with seaborn
df = pd.DataFrame(array, columns=['A', 'B', 'C'])

# Create a heatmap using seaborn
sns.heatmap(df, annot=True, cmap='viridis')
plt.title('Heatmap of array')
plt.show()